version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - DB_HOST=datastore
      - DB_DATABASE=sys
      - DB_USERNAME=root
      - DB_PASSWORD=root
    restart: always

